apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-addons-argocd-server
  annotations:
    kubernetes.io/ingress.class: contour
spec:
  rules:
  - host: "k8s-addons-argocd-server.dev-1.gs.gcp.com"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: k8s-addons-argocd-server
          servicePort: 80