apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: k8s-addons-argocd-server
spec:
  rules:
  - host: "k8s-addons-argocd-server.dev-1.gs.gcp.com"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: k8s-addons-argocd-server
          servicePort: 80